Repository openshift/pipelines-catalog, pull requests merged in 2019-06, with the labels that each got.

#1 Add a README and OWNERS file
  OWNERS
  README.md
Labels: lgtm, size/S

#2 Add s2i builder images task
  s2i-dotnet/s2i-dotnet-task.yaml
  s2i-go/s2i-go-task.yaml
  s2i-java11/s2i-java-11-task.yaml
  s2i-java8/s2i-java-8-task.yaml
  s2i-nodejs/s2i-nodejs-task.yaml
  s2i-perl/s2i-perl-5-task.yaml
  s2i-php/s2i-php-7-task.yaml
  s2i-python2/s2i-python-2-task.yaml
  s2i-python3/s2i-python-3-task.yaml
  s2i-ruby/s2i-ruby-2-task.yaml
Labels: approved, lgtm, size/XL

#6 Refactor folder names
  s2i-dotnet-1/README.md
  s2i-dotnet-1/s2i-dotnet-1-task.yaml
  s2i-dotnet-2/README.md
  s2i-dotnet-2/s2i-dotnet-2-task.yaml
  s2i-java-11/README.md
  s2i-java-11/s2i-java-11-task.yaml
  s2i-java-8/README.md
  s2i-java-8/s2i-java-8-task.yaml
  s2i-python-2/README.md
  s2i-python-2/s2i-python-2-task.yaml
  s2i-python-3/README.md
  s2i-python-3/s2i-python-3-task.yaml
Labels: approved, lgtm, size/S

#7 Minor edits for consistency
  s2i-nodejs/README.md
Labels: approved, lgtm, size/S
