Repository openshift/pipelines-catalog, pull requests merged in 2020-07, with the labels that each got.

#40 Fix s2i-python-2 tests
  s2i-python-2-workspace/tests/run.yaml
  s2i-python-2/tests/resources.yaml
Labels: approved, lgtm

#24 EAP CD s2i Task added
  s2i-eap/README.md
  s2i-eap/s2i-eap-task.yaml
Labels: approved, lgtm, size/L

#42 Fix path for git clone task yaml
  s2i-dotnet-1-workspace/tests/pre-apply-task-hook.sh
  s2i-dotnet-2-workspace/tests/pre-apply-task-hook.sh
  s2i-go-workspace/tests/pre-apply-task-hook.sh
  s2i-java-11-workspace/tests/pre-apply-task-hook.sh
  s2i-java-8-workspace/tests/pre-apply-task-hook.sh
  s2i-nodejs-workspace/tests/pre-apply-task-hook.sh
  s2i-perl-workspace/tests.disabled/pre-apply-task-hook.sh
  s2i-php-workspace/tests/pre-apply-task-hook.sh
  s2i-python-2-workspace/tests/pre-apply-task-hook.sh
  s2i-python-3-workspace/tests/pre-apply-task-hook.sh
  s2i-ruby-workspace/tests/pre-apply-task-hook.sh
Labels: approved, lgtm

#44 Change spring petclinic to fork
  task/s2i-java-11-workspace/0.1/tests/run.yaml
  task/s2i-java-11/0.1/tests/resources.yaml
Labels: approved, lgtm

#45 Fix s2i java 11 workspace run
  task/s2i-java-11-workspace/0.1/tests/run.yaml
Labels: approved, lgtm

#46 Fix python example
  task/s2i-python-2-workspace/0.1/tests/run.yaml
  task/s2i-python-2/0.1/tests/resources.yaml
Labels: lgtm

#47 s2i-eap: migrate task to v1beta1 API
  task/s2i-eap/0.1/README.md
  task/s2i-eap/0.1/s2i-eap.yaml
Labels: approved, lgtm

#49 Refactor naming and structure
  task/s2i-dotnet-1-pr/0.1/README.md
  task/s2i-dotnet-1-pr/0.1/s2i-dotnet-1-pr.yaml
  task/s2i-dotnet-1/0.1/README.md
  task/s2i-dotnet-1/0.1/s2i-dotnet-1.yaml
  task/s2i-dotnet-2-pr/0.1/README.md
  task/s2i-dotnet-2-pr/0.1/s2i-dotnet-2-pr.yaml
  task/s2i-dotnet-2/0.1/README.md
  task/s2i-dotnet-2/0.1/s2i-dotnet-2.yaml
  task/s2i-dotnet-3-pr/0.1/README.md
  task/s2i-dotnet-3-pr/0.1/s2i-dotnet-3-pr.yaml
  task/s2i-dotnet-3/0.1/README.md
  task/s2i-eap-pr/0.1/README.md
  task/s2i-eap-pr/0.1/s2i-eap-pr.yaml
  task/s2i-eap/0.1/README.md
  task/s2i-go-pr/0.1/README.md
  task/s2i-go-pr/0.1/s2i-go-pr.yaml
  task/s2i-go/0.1/README.md
  task/s2i-java-11-pr/0.1/README.md
  task/s2i-java-11-pr/0.1/s2i-java-11-pr.yaml
  task/s2i-java-11-pr/0.1/s2i-java-11.yaml
  task/s2i-java-11/0.1/README.md
  task/s2i-java-11/0.1/s2i-java-11.yaml
  task/s2i-java-8-pr/0.1/README.md
  task/s2i-java-8-pr/0.1/s2i-java-8-pr.yaml
  task/s2i-java-8/0.1/README.md
  task/s2i-java-8/0.1/s2i-java-8.yaml
  task/s2i-nodejs-pr/0.1/README.md
  task/s2i-nodejs-pr/0.1/s2i-nodejs.yaml
  task/s2i-nodejs/0.1/README.md
  task/s2i-nodejs/0.1/s2i-nodejs.yaml
  task/s2i-perl-pr/0.1/README.md
  task/s2i-perl-pr/0.1/s2i-perl-pr.yaml
  task/s2i-perl/0.1/README.md
  task/s2i-perl/0.1/s2i-perl.yaml
  task/s2i-php-pr/0.1/README.md
  task/s2i-php-pr/0.1/s2i-php-pr.yaml
  task/s2i-php/0.1/README.md
  task/s2i-php/0.1/s2i-php.yaml
  task/s2i-python-2-pr/0.1/README.md
  task/s2i-python-2-pr/0.1/s2i-python-2-pr.yaml
  task/s2i-python-2/0.1/README.md
  task/s2i-python-2/0.1/s2i-python-2.yaml
  task/s2i-python-3-pr/0.1/s2i-python-3-pr.yaml
  task/s2i-python-3/0.1/README.md
  task/s2i-python-3/0.1/s2i-python-3.yaml
  task/s2i-ruby-pr/0.1/README.md
  task/s2i-ruby-pr/0.1/s2i-ruby-pr.yaml
  task/s2i-ruby/0.1/README.md
  task/s2i-ruby/0.1/s2i-ruby.yaml
Labels: approved, lgtm

#50 Fix file name for nodejs-pr task
  task/s2i-nodejs-pr/0.1/s2i-nodejs-pr.yaml
Labels: approved, lgtm

#51 Fix dotnet3 task
  task/s2i-dotnet-3/0.1/s2i-dotnet-3.yaml
Labels: approved, lgtm
