Repository openshift/pipelines-catalog, pull requests merged in 2020-02, with the labels that each got.

#21 Add dotnet core 3 task
  s2i-dotnet-3/README.md
  s2i-dotnet-3/s2i-dotnet-3-task.yaml
  s2i-dotnet-3/tests/pre-apply-task-hook.sh
  s2i-dotnet-3/tests/resources.yaml
  s2i-dotnet-3/tests/run.yaml
Labels: approved, lgtm, ok-to-test, size/L

#22 Add buildah image tag inspite of latest
  s2i-dotnet-1/s2i-dotnet-1-task.yaml
  s2i-dotnet-1/tests/run.yaml
  s2i-dotnet-2/README.md
  s2i-dotnet-2/s2i-dotnet-2-task.yaml
  s2i-dotnet-3/README.md
  s2i-dotnet-3/s2i-dotnet-3-task.yaml
  s2i-go/s2i-go-task.yaml
  s2i-java-11/s2i-java-11-task.yaml
  s2i-java-8/s2i-java-8-task.yaml
  s2i-nodejs/s2i-nodejs-task.yaml
  s2i-perl/s2i-perl-task.yaml
  s2i-php/s2i-php-task.yaml
  s2i-python-2/s2i-python-2-task.yaml
  s2i-python-3/s2i-python-3-task.yaml
  s2i-ruby/s2i-ruby-task.yaml
Labels: approved, lgtm, size/M

#23 Rename serviceAccount to serviceAccountName in README.md
  s2i-dotnet-1/README.md
  s2i-dotnet-2/README.md
  s2i-dotnet-3/README.md
  s2i-go/README.md
  s2i-java-11/README.md
  s2i-java-8/README.md
  s2i-nodejs/README.md
  s2i-perl/README.md
  s2i-php/README.md
  s2i-python-2/README.md
  s2i-python-3/README.md
  s2i-ruby/README.md
Labels: approved, lgtm, size/S
